# 데이터 전처리

## 1. 데이터 불러오기

* 월별데이터(시장)
* 일별데이터(가격,종합,희소,환율)

In [4]:
import pandas as pd
가격=pd.read_csv('../data/리튬/리튬가격.csv')
종합=pd.read_csv('../data/리튬/광물종합지수.csv',encoding='cp949')
시장=pd.read_csv('../data/리튬/시장전망지표.csv')
희소=pd.read_csv('../data/리튬/희소금속지수.csv',encoding='cp949')
환율=pd.read_csv('../data/리튬/위안.csv',encoding='cp949')
탄산리튬=pd.read_csv('../data/리튬/탄산리튬.csv',encoding='cp949')
수산화리튬=pd.read_csv('../data/리튬/수산화리튬.csv',encoding='cp949')
수급안정화=pd.read_csv('../data/리튬/수급안정화.csv')

In [5]:
수급안정화=수급안정화[['기준일','수급안정화지수']]
수급안정화

        기준일  수급안정화지수
0   2017-01    12.01
1   2017-02    11.44
2   2017-03    11.45
3   2017-04    11.06
4   2017-05     9.91
..      ...      ...
85  2024-02    73.96
86  2024-03    73.82
87  2024-04    71.25
88  2024-05    69.38
89  2024-06    70.42

[90 rows x 2 columns]

In [6]:
#가격데이터는 06-06까지 -> 주말은 빠진다.
가격2=가격[가격['기준일']<'2024-05-21']
가격2.tail(5)

            기준일   기준가격  등락가  등락비율  재고량
713  2024-05-14  106.5  0.0  0.00    0
714  2024-05-15  103.5 -3.0 -2.82    0
715  2024-05-16  103.5  0.0  0.00    0
716  2024-05-17  103.5  0.0  0.00    0
717  2024-05-20  103.5  0.0  0.00    0

In [7]:
# 광물 종합지수는 5.20까지 -> 주말은 제외된다.
종합.tail(10)

,기준일,광물종합지수,등락가,등락율(퍼센트),이동평균(10),이동평균(20),이동평균(60),이동평균(120),이동평균(200),볼린저밴드(하한선),...,상한이격률,투자심리선,상대강도지수(RSI),이동평균 수렴확산(MACD),시그널,이격도(10),이격도(20),이격도(60),이격도(120),이격도(200)
3175,2024-05-07,2926.744285,2.078236,0.000711,2916.083441,2880.002635,2746.890275,2732.913121,2753.280139,2753.525733,...,0.026521,0.7,0.682149,0.053822,0.018396,0.003656,0.016230,0.065475,0.070925,0.063003
3176,2024-05-08,2947.205125,20.460840,0.006991,2922.202903,2890.200489,2751.735457,2734.305887,2753.943105,2778.075214,...,0.018359,0.8,0.652929,0.057014,0.021768,0.008556,0.019723,0.071035,0.077862,0.070176
3177,2024-05-09,2918.406309,-28.798816,-0.009772,2924.451981,2897.484064,2756.208533,2735.427665,2754.411250,2799.446757,...,0.025743,0.7,0.489603,0.059244,0.025190,-0.002067,0.007221,0.058848,0.066892,0.059539
3178,2024-05-10,2898.537472,-19.868837,-0.006808,2922.576933,2904.198823,2760.194604,2736.389026,2754.948969,2828.805514,...,0.027203,0.6,0.387600,0.061325,0.028643,-0.008225,-0.001949,0.050121,0.059256,0.052120
3179,2024-05-13,2916.080354,17.542882,0.006052,2923.210789,2909.537923,2764.376992,2737.655697,2755.643892,2848.728177,...,0.018270,0.7,0.468533,0.062784,0.032066,-0.002439,0.002249,0.054878,0.065174,0.058221
3180,2024-05-14,2904.495116,-11.585238,-0.003973,2921.978376,2912.672906,2768.582882,2738.799079,2756.438774,2860.752932,...,0.020272,0.6,0.551064,0.063485,0.035377,-0.005983,-0.002808,0.049091,0.060500,0.053713
3181,2024-05-15,2883.468771,-21.026345,-0.007239,2917.241904,2915.162442,2772.777281,2739.860338,2757.246568,2875.978039,...,0.023991,0.5,0.467606,0.063982,0.038574,-0.011577,-0.010872,0.039921,0.052415,0.045778
3182,2024-05-16,2908.732163,25.263392,0.008761,2914.801576,2916.816736,2776.876349,2741.087662,2758.086599,2882.120089,...,0.014495,0.5,0.478175,0.064109,0.041612,-0.002082,-0.002772,0.047484,0.061160,0.054620
3183,2024-05-17,2923.022685,14.290522,0.004913,2915.135833,2916.823483,2781.214806,2742.398255,2758.955338,2882.121813,...,0.009657,0.6,0.532752,0.063603,0.044436,0.002705,0.002125,0.050988,0.065864,0.059467
3184,2024-05-20,2962.905545,39.882859,0.013644,2918.959783,2917.658274,2786.222895,2744.028505,2760.086494,2879.362897,...,-0.002352,0.6,0.597825,0.063275,0.047030,0.015055,0.015508,0.063413,0.079765,0.073483

In [8]:
# 환율은 6-13까지 -> 주말제외
환율2=환율[환율['Date']<'2024-05-21']
환율2.tail(5)

           Date       Close
813  2024-05-14  188.569345
814  2024-05-15  188.397894
815  2024-05-16  187.538963
816  2024-05-17  186.509635
817  2024-05-20  187.380065

In [9]:
#시장은 5월까지
시장.tail(5)

         기준일  시장전망지표  전월대비  등락가  전월대비 등락율
192  2024-01   77.84       6.16      8.60
193  2024-02   79.88       2.05      2.63
194  2024-03   79.73      -0.15     -0.19
195  2024-04   76.95      -2.78     -3.48
196  2024-05   74.94      -2.02     -2.62

In [10]:
#희소는 5-20까지
희소.tail(5)

             기준일       희유금속지수
3180  2024-05-14  1845.162442
3181  2024-05-15  1845.162442
3182  2024-05-16  1845.162442
3183  2024-05-17  1845.162442
3184  2024-05-20  1815.483543

In [11]:
수산화리튬2=수산화리튬[['기간','수산화리튬 수출 중량','수산화리튬 수입 중량']]
수산화리튬2['수산화리튬 수출입']=수산화리튬2['수산화리튬 수출 중량']-수산화리튬['수산화리튬 수입 중량']
수산화리튬2.tail()

C:\Users\wandong\AppData\Local\Temp\ipykernel_14068\3837663985.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  수산화리튬2['수산화리튬 수출입']=수산화리튬2['수산화리튬 수출 중량']-수산화리튬['수산화리튬 수입 중량']

         기간  수산화리튬 수출 중량  수산화리튬 수입 중량  수산화리튬 수출입
31  2024-01          3.0       7827.4    -7824.4
32  2024-02         11.1       8408.7    -8397.6
33  2024-03          0.2      10260.1   -10259.9
34  2024-04         38.1       9062.7    -9024.6
35  2024-05          4.5       9358.9    -9354.4

In [12]:
탄산리튬2=탄산리튬[['기간','탄산리튬 수출 중량','탄산리튬 수입 중량']]
탄산리튬2['수산화리튬 수출입']=탄산리튬2['탄산리튬 수출 중량']-탄산리튬['탄산리튬 수입 중량']
탄산리튬2.head(5)

C:\Users\wandong\AppData\Local\Temp\ipykernel_14068\728476328.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  탄산리튬2['수산화리튬 수출입']=탄산리튬2['탄산리튬 수출 중량']-탄산리튬['탄산리튬 수입 중량']

        기간  탄산리튬 수출 중량  탄산리튬 수입 중량  수산화리튬 수출입
0  2021-06       123.5      4972.3    -4848.8
1  2021-07       749.0      3598.9    -2849.9
2  2021-08       344.1      2775.5    -2431.4
3  2021-09       218.9      3025.3    -2806.4
4  2021-10       390.2      4566.9    -4176.7

## 2. 데이터 살펴보기

광물가격데이터에서 다음 날짜가 휴일임에도 불구하고 존재함(제거)

- 2021.09.18
- 2021.09.26
- 2022.04.02
- 2022.04.26
- 2023.05.06 (내생일 ㅋ)
- 2023.06.25
- 2024.02.04
- 2024.04.28
- 2024.05.11

In [13]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#가격 종합 환율 시장 희소

tmp=pd.merge(가격2,종합,on='기준일',how='left')
tmp[tmp['광물종합지수'].isna()==True]['기준일']

72     2021-09-18
76     2021-09-26
199    2022-04-02
213    2022-04-24
221    2022-05-07
455    2023-04-23
463    2023-05-06
497    2023-06-25
650    2024-02-04
687    2024-04-07
703    2024-04-28
711    2024-05-11
Name: 기준일, dtype: object

In [14]:
결측일자=['2021-09-18','2021-09-26','2022-04-02','2022-04-24','2022-05-07',
     '2023-04-23','2023-05-06','2023-06-25','2024-02-04','2024-04-07','2024-04-28','2024-05-11']

가격3=가격2[~가격2['기준일'].isin(결측일자)]
가격3

            기준일   기준가격  등락가  등락비율  재고량
0    2021-06-09   81.0  0.0  0.00    0
1    2021-06-10   81.0  0.0  0.00    0
2    2021-06-11   81.0  0.0  0.00    0
3    2021-06-15   81.0  0.0  0.00    0
4    2021-06-16   81.0  0.0  0.00    0
..          ...    ...  ...   ...  ...
713  2024-05-14  106.5  0.0  0.00    0
714  2024-05-15  103.5 -3.0 -2.82    0
715  2024-05-16  103.5  0.0  0.00    0
716  2024-05-17  103.5  0.0  0.00    0
717  2024-05-20  103.5  0.0  0.00    0

[706 rows x 5 columns]

In [15]:
가격종합=pd.merge(가격3,종합,on='기준일',how='left')
가격종합.isna().sum()

기준일                0
기준가격               0
등락가_x              0
등락비율               0
재고량                0
광물종합지수             0
등락가_y              0
등락율(퍼센트)           0
이동평균(10)           0
이동평균(20)           0
이동평균(60)           0
이동평균(120)          0
이동평균(200)          0
볼린저밴드(하한선)         0
볼린저밴드(중심선)         0
볼린저밴드(상한선)         0
표준편차(20)           0
하한이격률              0
상한이격률              0
투자심리선              0
상대강도지수(RSI)        0
이동평균 수렴확산(MACD)    0
시그널                0
이격도(10)            0
이격도(20)            0
이격도(60)            0
이격도(120)           0
이격도(200)           0
dtype: int64

In [16]:
가격종합환율=pd.merge(가격종합,환율,left_on='기준일',right_on='Date',how='left')
가격종합환율.isna().sum()

기준일                0
기준가격               0
등락가_x              0
등락비율               0
재고량                0
광물종합지수             0
등락가_y              0
등락율(퍼센트)           0
이동평균(10)           0
이동평균(20)           0
이동평균(60)           0
이동평균(120)          0
이동평균(200)          0
볼린저밴드(하한선)         0
볼린저밴드(중심선)         0
볼린저밴드(상한선)         0
표준편차(20)           0
하한이격률              0
상한이격률              0
투자심리선              0
상대강도지수(RSI)        0
이동평균 수렴확산(MACD)    0
시그널                0
이격도(10)            0
이격도(20)            0
이격도(60)            0
이격도(120)           0
이격도(200)           0
Date               0
Close              0
dtype: int64

In [17]:
가격종합환율희소=pd.merge(가격종합환율,희소,on='기준일',how='left')
가격종합환율희소.isna().sum()

기준일                0
기준가격               0
등락가_x              0
등락비율               0
재고량                0
광물종합지수             0
등락가_y              0
등락율(퍼센트)           0
이동평균(10)           0
이동평균(20)           0
이동평균(60)           0
이동평균(120)          0
이동평균(200)          0
볼린저밴드(하한선)         0
볼린저밴드(중심선)         0
볼린저밴드(상한선)         0
표준편차(20)           0
하한이격률              0
상한이격률              0
투자심리선              0
상대강도지수(RSI)        0
이동평균 수렴확산(MACD)    0
시그널                0
이격도(10)            0
이격도(20)            0
이격도(60)            0
이격도(120)           0
이격도(200)           0
Date               0
Close              0
희유금속지수             0
dtype: int64

In [18]:
가격종합환율희소=가격종합환율희소[['기준일','기준가격','광물종합지수','희유금속지수','Close']]
가격종합환율희소

            기준일   기준가격       광물종합지수       희유금속지수       Close
0    2021-06-09   81.0  2407.510943  1682.471447  174.527703
1    2021-06-10   81.0  2436.458355  1682.471447  174.807806
2    2021-06-11   81.0  2452.915918  1682.471447  173.843528
3    2021-06-15   81.0  2496.551463  1741.940418  174.501333
4    2021-06-16   81.0  2466.150328  1741.940418  174.243559
..          ...    ...          ...          ...         ...
701  2024-05-14  106.5  2904.495116  1845.162442  188.569345
702  2024-05-15  103.5  2883.468771  1845.162442  188.397894
703  2024-05-16  103.5  2908.732163  1845.162442  187.538963
704  2024-05-17  103.5  2923.022685  1845.162442  186.509635
705  2024-05-20  103.5  2962.905545  1815.483543  187.380065

[706 rows x 5 columns]

In [19]:
# 기존 데이터에서 에서 연도와월만 저장하여 시장과 merge

가격종합환율희소['기준연월']=가격종합환율희소['기준일'].str[:7]
가격종합환율희소

            기준일   기준가격       광물종합지수       희유금속지수       Close     기준연월
0    2021-06-09   81.0  2407.510943  1682.471447  174.527703  2021-06
1    2021-06-10   81.0  2436.458355  1682.471447  174.807806  2021-06
2    2021-06-11   81.0  2452.915918  1682.471447  173.843528  2021-06
3    2021-06-15   81.0  2496.551463  1741.940418  174.501333  2021-06
4    2021-06-16   81.0  2466.150328  1741.940418  174.243559  2021-06
..          ...    ...          ...          ...         ...      ...
701  2024-05-14  106.5  2904.495116  1845.162442  188.569345  2024-05
702  2024-05-15  103.5  2883.468771  1845.162442  188.397894  2024-05
703  2024-05-16  103.5  2908.732163  1845.162442  187.538963  2024-05
704  2024-05-17  103.5  2923.022685  1845.162442  186.509635  2024-05
705  2024-05-20  103.5  2962.905545  1815.483543  187.380065  2024-05

[706 rows x 6 columns]

In [20]:
final=pd.merge(가격종합환율희소,시장,left_on='기준연월',right_on='기준일',how='left')
final.isna().sum()

기준일_x        0
기준가격         0
광물종합지수       0
희유금속지수       0
Close        0
기준연월         0
기준일_y        0
시장전망지표       0
전월대비  등락가    0
전월대비 등락율     0
dtype: int64

In [21]:
final

,기준일_x,기준가격,광물종합지수,희유금속지수,Close,기준연월,기준일_y,시장전망지표,전월대비 등락가,전월대비 등락율
0,2021-06-09,81.0,2407.510943,1682.471447,174.527703,2021-06,2021-06,35.06,0.97,2.86
1,2021-06-10,81.0,2436.458355,1682.471447,174.807806,2021-06,2021-06,35.06,0.97,2.86
2,2021-06-11,81.0,2452.915918,1682.471447,173.843528,2021-06,2021-06,35.06,0.97,2.86
3,2021-06-15,81.0,2496.551463,1741.940418,174.501333,2021-06,2021-06,35.06,0.97,2.86
4,2021-06-16,81.0,2466.150328,1741.940418,174.243559,2021-06,2021-06,35.06,0.97,2.86
...,...,...,...,...,...,...,...,...,...,...
701,2024-05-14,106.5,2904.495116,1845.162442,188.569345,2024-05,2024-05,74.94,-2.02,-2.62
702,2024-05-15,103.5,2883.468771,1845.162442,188.397894,2024-05,2024-05,74.94,-2.02,-2.62
703,2024-05-16,103.5,2908.732163,1845.162442,187.538963,2024-05,2024-05,74.94,-2.02,-2.62
704,2024-05-17,103.5,2923.022685,1845.162442,186.509635,2024-05,2024-05,74.94,-2.02,-2.62
705,2024-05-20,103.5,2962.905545,1815.483543,187.380065,2024-05,2024-05,74.94,-2.02,-2.62

In [22]:
수산화리튬

,기간,HS코드,품목명,수산화리튬 수출 중량,수출 금액,수산화리튬 수입 중량,수입 금액,무역수지
0,2021-06,2825202000,수산화리튬,74.7,732,5111.1,60489,-59756
1,2021-07,2825202000,수산화리튬,42.0,372,2943.0,34710,-34338
2,2021-08,2825202000,수산화리튬,393.2,3057,5194.3,64514,-61457
3,2021-09,2825202000,수산화리튬,1.9,146,4579.7,57363,-57217
4,2021-10,2825202000,수산화리튬,120.3,901,4520.4,57747,-56846
5,2021-11,2825202000,수산화리튬,36.8,267,4806.4,71254,-70986
6,2021-12,2825202000,수산화리튬,22.4,150,5888.9,98833,-98684
7,2022-01,2825202000,수산화리튬,9.6,97,6157.7,127983,-127886
8,2022-02,2825202000,수산화리튬,57.0,1425,3048.6,63927,-62502
9,2022-03,2825202000,수산화리튬,10.0,149,5408.4,172296,-172147
10,2022-04,2825202000,수산화리튬,0.5,2,3919.5,159402,-159399
11,2022-05,2825202000,수산화리튬,0.0,1,5922.3,341947,-341946
12,2022-06,2825202000,수산화리튬,1.9,34,8364.4,533941,-533907
13,2022-07,2825202000,수산화리튬,80.5,2271,5720.3,337407,-335136
14,2022-08,2825202000,수산화리튬,5.5,323,6030.4,385237,-384914
15,2022-09,2825202000,수산화리튬,127.8,333,5664.8,346321,-345988
16,2022-10,2825202000,수산화리튬,11.7,770,7474.9,435541,-434771
17,2022-11,2825202000,수산화리튬,12.4,74,6128.8,355212,-355138
18,2022-12,2825202000,수산화리튬,505.4,34343,7030.7,401530,-367188
19,2023-01,2825202000,수산화리튬,1.8,140,8454.3,647230,-647090
20,2023-02,2825202000,수산화리튬,10.1,630,8754.3,675190,-674560
21,2023-03,2825202000,수산화리튬,108.0,9342,11907.3,837725,-828383
22,2023-04,2825202000,수산화리튬,0.0,0,8524.1,550885,-550885
23,2023-05,2825202000,수산화리튬,2.0,170,8723.6,464634,-464464
24,2023-06,2825202000,수산화리튬,220.1,15625,9596.9,522362,-506737
25,2023-07,2825202000,수산화리튬,247.5,17062,9952.6,495432,-478370
26,2023-08,2825202000,수산화리튬,0.0,0,10345.2,493567,-493567
27,2023-09,2825202000,수산화리튬,6.5,231,9624.5,399062,-398832
28,2023-10,2825202000,수산화리튬,236.8,10710,9097.1,331685,-320975
29,2023-11,2825202000,수산화리튬,982.1,46279,12763.5,414208,-367929
30,2023-12,2825202000,수산화리튬,450.9,21704,11974.3,354051,-332348
31,2024-01,2825202000,수산화리튬,3.0,48,7827.4,170490,-170442
32,2024-02,2825202000,수산화리튬,11.1,230,8408.7,156551,-156321
33,2024-03,2825202000,수산화리튬,0.2,16,10260.1,172691,-172674
34,2024-04,2825202000,수산화리튬,38.1,509,9062.7,144866,-144357
35,2024-05,2825202000,수산화리튬,4.5,66,9358.9,160120,-160053

In [23]:
final2=pd.merge(final,수산화리튬,left_on='기준연월',right_on='기간',how='left')
final2.isna().sum()

기준일_x          0
기준가격           0
광물종합지수         0
희유금속지수         0
Close          0
기준연월           0
기준일_y          0
시장전망지표         0
전월대비  등락가      0
전월대비 등락율       0
기간             0
HS코드           0
품목명            0
수산화리튬 수출 중량    0
수출 금액          0
수산화리튬 수입 중량    0
수입 금액          0
무역수지           0
dtype: int64

In [24]:
final3=pd.merge(final2,탄산리튬,left_on='기준연월',right_on='기간',how='left')
final3.isna().sum()

기준일_x          0
기준가격           0
광물종합지수         0
희유금속지수         0
Close          0
기준연월           0
기준일_y          0
시장전망지표         0
전월대비  등락가      0
전월대비 등락율       0
기간_x           0
HS코드_x         0
품목명_x          0
수산화리튬 수출 중량    0
수출 금액_x        0
수산화리튬 수입 중량    0
수입 금액_x        0
무역수지_x         0
기간_y           0
HS코드_y         0
품목명_y          0
탄산리튬 수출 중량     0
수출 금액_y        0
탄산리튬 수입 중량     0
수입 금액_y        0
무역수지_y         0
dtype: int64

In [25]:
final3

,기준일_x,기준가격,광물종합지수,희유금속지수,Close,기준연월,기준일_y,시장전망지표,전월대비 등락가,전월대비 등락율,...,수입 금액_x,무역수지_x,기간_y,HS코드_y,품목명_y,탄산리튬 수출 중량,수출 금액_y,탄산리튬 수입 중량,수입 금액_y,무역수지_y
0,2021-06-09,81.0,2407.510943,1682.471447,174.527703,2021-06,2021-06,35.06,0.97,2.86,...,60489,-59756,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671
1,2021-06-10,81.0,2436.458355,1682.471447,174.807806,2021-06,2021-06,35.06,0.97,2.86,...,60489,-59756,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671
2,2021-06-11,81.0,2452.915918,1682.471447,173.843528,2021-06,2021-06,35.06,0.97,2.86,...,60489,-59756,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671
3,2021-06-15,81.0,2496.551463,1741.940418,174.501333,2021-06,2021-06,35.06,0.97,2.86,...,60489,-59756,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671
4,2021-06-16,81.0,2466.150328,1741.940418,174.243559,2021-06,2021-06,35.06,0.97,2.86,...,60489,-59756,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,2024-05-14,106.5,2904.495116,1845.162442,188.569345,2024-05,2024-05,74.94,-2.02,-2.62,...,160120,-160053,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902
702,2024-05-15,103.5,2883.468771,1845.162442,188.397894,2024-05,2024-05,74.94,-2.02,-2.62,...,160120,-160053,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902
703,2024-05-16,103.5,2908.732163,1845.162442,187.538963,2024-05,2024-05,74.94,-2.02,-2.62,...,160120,-160053,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902
704,2024-05-17,103.5,2923.022685,1845.162442,186.509635,2024-05,2024-05,74.94,-2.02,-2.62,...,160120,-160053,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902
705,2024-05-20,103.5,2962.905545,1815.483543,187.380065,2024-05,2024-05,74.94,-2.02,-2.62,...,160120,-160053,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902

In [28]:
final4=pd.merge(final3,수급안정화,left_on='기준연월',right_on='기준일',how='left')
final4

,기준일_x,기준가격,광물종합지수,희유금속지수,Close,기준연월,기준일_y,시장전망지표,전월대비 등락가,전월대비 등락율,...,기간_y,HS코드_y,품목명_y,탄산리튬 수출 중량,수출 금액_y,탄산리튬 수입 중량,수입 금액_y,무역수지_y,기준일,수급안정화지수
0,2021-06-09,81.0,2407.510943,1682.471447,174.527703,2021-06,2021-06,35.06,0.97,2.86,...,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671,2021-06,32.46
1,2021-06-10,81.0,2436.458355,1682.471447,174.807806,2021-06,2021-06,35.06,0.97,2.86,...,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671,2021-06,32.46
2,2021-06-11,81.0,2452.915918,1682.471447,173.843528,2021-06,2021-06,35.06,0.97,2.86,...,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671,2021-06,32.46
3,2021-06-15,81.0,2496.551463,1741.940418,174.501333,2021-06,2021-06,35.06,0.97,2.86,...,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671,2021-06,32.46
4,2021-06-16,81.0,2466.150328,1741.940418,174.243559,2021-06,2021-06,35.06,0.97,2.86,...,2021-06,2836910000,탄산리튬,123.5,1678,4972.3,49349,-47671,2021-06,32.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,2024-05-14,106.5,2904.495116,1845.162442,188.569345,2024-05,2024-05,74.94,-2.02,-2.62,...,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902,2024-05,69.38
702,2024-05-15,103.5,2883.468771,1845.162442,188.397894,2024-05,2024-05,74.94,-2.02,-2.62,...,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902,2024-05,69.38
703,2024-05-16,103.5,2908.732163,1845.162442,187.538963,2024-05,2024-05,74.94,-2.02,-2.62,...,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902,2024-05,69.38
704,2024-05-17,103.5,2923.022685,1845.162442,186.509635,2024-05,2024-05,74.94,-2.02,-2.62,...,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902,2024-05,69.38
705,2024-05-20,103.5,2962.905545,1815.483543,187.380065,2024-05,2024-05,74.94,-2.02,-2.62,...,2024-05,2836910000,탄산리튬,504.6,6658,2793.1,48560,-41902,2024-05,69.38

In [30]:
final5=final4[['기준일_x','기준가격','광물종합지수','희유금속지수','Close','시장전망지표','수산화리튬 수출 중량','수산화리튬 수입 중량',
            '탄산리튬 수출 중량','탄산리튬 수입 중량','무역수지_x','무역수지_y','수급안정화지수']]
final5.rename(columns={'기준일_x':'기준일','Close':'환율','무역수지_x':'수산화리튬_무역수지','무역수지_y':'탄산리튬_무역수지'},inplace=True)
final5

C:\Users\wandong\AppData\Local\Temp\ipykernel_14068\1863057263.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final5.rename(columns={'기준일_x':'기준일','Close':'환율','무역수지_x':'수산화리튬_무역수지','무역수지_y':'탄산리튬_무역수지'},inplace=True)

,기준일,기준가격,광물종합지수,희유금속지수,환율,시장전망지표,수산화리튬 수출 중량,수산화리튬 수입 중량,탄산리튬 수출 중량,탄산리튬 수입 중량,수산화리튬_무역수지,탄산리튬_무역수지,수급안정화지수
0,2021-06-09,81.0,2407.510943,1682.471447,174.527703,35.06,74.7,5111.1,123.5,4972.3,-59756,-47671,32.46
1,2021-06-10,81.0,2436.458355,1682.471447,174.807806,35.06,74.7,5111.1,123.5,4972.3,-59756,-47671,32.46
2,2021-06-11,81.0,2452.915918,1682.471447,173.843528,35.06,74.7,5111.1,123.5,4972.3,-59756,-47671,32.46
3,2021-06-15,81.0,2496.551463,1741.940418,174.501333,35.06,74.7,5111.1,123.5,4972.3,-59756,-47671,32.46
4,2021-06-16,81.0,2466.150328,1741.940418,174.243559,35.06,74.7,5111.1,123.5,4972.3,-59756,-47671,32.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,2024-05-14,106.5,2904.495116,1845.162442,188.569345,74.94,4.5,9358.9,504.6,2793.1,-160053,-41902,69.38
702,2024-05-15,103.5,2883.468771,1845.162442,188.397894,74.94,4.5,9358.9,504.6,2793.1,-160053,-41902,69.38
703,2024-05-16,103.5,2908.732163,1845.162442,187.538963,74.94,4.5,9358.9,504.6,2793.1,-160053,-41902,69.38
704,2024-05-17,103.5,2923.022685,1845.162442,186.509635,74.94,4.5,9358.9,504.6,2793.1,-160053,-41902,69.38
705,2024-05-20,103.5,2962.905545,1815.483543,187.380065,74.94,4.5,9358.9,504.6,2793.1,-160053,-41902,69.38

In [31]:
final5.to_csv('../data/final/리튬data.csv',encoding='cp949')